# Generated by Django 3.0.14 on 2021-09-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_mobile_number', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('quantity_unit', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('total_price', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(null=True)),
                ('items', models.ManyToManyField(related_name='order', to='order.ItemModel')),
            ],
        ),
    ]
